# Generated by Django 4.1.4 on 2023-01-03 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_category_alter_listing_image_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='auctions.listing'),
        ),
    ]
