# Generated by Django 4.1.4 on 2023-01-03 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_bids_bid_price_alter_bids_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='bid_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='commments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=5024)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='auctions.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
