# Generated by Django 4.1.4 on 2023-01-04 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_listing_watchlist_alter_commments_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchList',
        ),
        migrations.AddField(
            model_name='listing',
            name='watchList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watch', to=settings.AUTH_USER_MODEL),
        ),
    ]
